version: "3.8"

services:
    flask-app:
        build:
            context: .
            dockerfile: app.Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app

    scheduler:
        build:
            context: .
            dockerfile: scheduler.Dockerfile
        volumes:
            - .:/app
